### PR TITLE
Minor code to support file paths in raw string form

### PR DESCRIPTION
**Pull request by toshi09**
I made some changes to AbstractStorage class to support paths in raw string format instead of StorageKey. This helped me avoid repeated creation of StorageKey objects for OS/GCS path. I will be sending the PR for etl_renewfinancial soon where I have used these  helper class with GCS and local path manipulation.

### CODE REVIEW

**Comment by marcpareoee** [comment]
We're hoping to move away from using string paths in ETL. 

It is more convenient in the short run, but it's less maintainable in the long run. You find yourself wondering things like "is this a fully qualified path or a relative path"? It also makes commands like `tail` easier to use. You can compare the `mirror_path` usage in caltrack ETL to the `tail` usage in sharemydata ETL.

**Comment by marcpareoee** [comment]
The Key class definitely has room for extension / improvement -- that is where I would suggest thinking about how to improve things if implementation feels awkward.

**Comment by toshi09** [comment]
Sure, I will think about how  to add/improve StorageKey class. Will have to  resend PR.

**Comment by toshi09** [comment]
I have reverted back my changes with very minor change related to deleting temp files. I think we should remove initialization of base_path from AbstractStorage. AbstractStorage should only implement helper routines related to storage like, ls, get, put etc. The StorageKey should support base path and path manipulation related utils.

**Comment by toshi09** [comment]
@marcpare 
I am sending a PR for removing the default values of the env variables.
I will make the changes in .env file later, as my Develop repo needs to be clean slate to do so.
After i push these changes, i will immediately send a follow up PR.

**Comment by marcpareoee** [comment]
This looks good to merge. 

The thinking behind `base_path` in AbstractStorage is that it's convenient to only have to configure the base path in one place. Anyway, it's optional. 

StorageKey could definitely grow to include more features.

**Pull request merged**
